version: "3.9"

services:
  # ---------- Kafka (single-node KRaft) ----------
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: [ "CMD", "bash", "-lc", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- Kafka UI (Redpanda Console) ----------
  redpanda-console:
    image: docker.redpanda.com/redpanda/console:latest
    container_name: redpanda-console
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    command:
      - "--addr=0.0.0.0:8080"
      - "--kafka-brokers=kafka:9092"

  # ---------- MongoDB ----------
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ---------- Ollama (server) ----------
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  # ---------- Ollama model puller ----------
  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    entrypoint: [ "/bin/bash", "-lc", "sleep 3 && ollama pull llama3" ]
    volumes:
      - ollama_data:/root/.ollama
    restart: "no"

volumes:
  kafka_data:
  mongo_data:
  ollama_data:
